"""Initial schema

Revision ID: 120177e9e390
Revises: 
Create Date: 2026-04-17 23:39:28.784609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '120177e9e390'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactionevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sa.Enum('page_view', 'product_view', 'add_to_cart', 'purchase', 'click', 'dismiss', name='eventtype'), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactionevent_customer_id'), 'interactionevent', ['customer_id'], unique=False)
    op.create_index(op.f('ix_interactionevent_tenant_id'), 'interactionevent', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_interactionevent_timestamp'), 'interactionevent', ['timestamp'], unique=False)
    op.create_table('tenant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_index(op.f('ix_product_external_id'), 'product', ['external_id'], unique=False)
    op.create_index(op.f('ix_product_tenant_id'), 'product', ['tenant_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'power_user', 'operator', 'viewer', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_tenant_id'), 'user', ['tenant_id'], unique=False)


    op.create_table(
        "customer_features",
        sa.Column("id", sa.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("tenant_id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("customer_id", sa.Text(), nullable=False),
        sa.Column("total_views", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("total_cart_adds", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("total_purchases", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("distinct_products_viewed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("distinct_categories_viewed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("days_since_first_seen", sa.Integer(), nullable=True),
        sa.Column("days_since_last_activity", sa.Integer(), nullable=True),
        sa.Column("category_affinity", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("avg_days_between_purchases", sa.Float(), nullable=True),
        sa.Column("total_revenue", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("avg_order_value", sa.Numeric(12, 2), nullable=True),
        sa.Column("avg_session_duration_seconds", sa.Float(), nullable=True),
        sa.Column("avg_products_viewed_per_session", sa.Float(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("tenant_id", "customer_id", name="uq_customer_features_tenant_customer"),
    )
    op.create_index(
        "ix_customer_features_tenant_updated_at",
        "customer_features",
        ["tenant_id", "updated_at"],
        unique=False,
    )

    op.create_table(
        "pipeline_checkpoints",
        sa.Column("id", sa.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("tenant_id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("pipeline_name", sa.String(length=100), nullable=False),
        sa.Column("last_event_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("tenant_id", "pipeline_name", name="uq_pipeline_checkpoints_tenant_pipeline"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tenant_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_product_tenant_id'), table_name='product')
    op.drop_index(op.f('ix_product_external_id'), table_name='product')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_interactionevent_timestamp'), table_name='interactionevent')
    op.drop_index(op.f('ix_interactionevent_tenant_id'), table_name='interactionevent')
    op.drop_index(op.f('ix_interactionevent_customer_id'), table_name='interactionevent')
    op.drop_table('interactionevent')

    op.drop_table("pipeline_checkpoints")
    op.drop_index("ix_customer_features_tenant_updated_at", table_name="customer_features")
    op.drop_table("customer_features")
    # ### end Alembic commands ###
